default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: abroadinquiry_development

test:
  <<: *default
  database: abroadinquiry_test

production:
  <<: *default
  database: abroadinquiry_development
